### ISSUE TITLE
PGGB for bacterial Plasmids?

### ISSUE THREAD

**Issue by UpalabdhaD** [ZoeYang2020/Pangenome-Graphs-in-Infectious-Disease#1]
Dear authors,
Glad to find the repo. Super interestiing and useful codes.

However, we I look into the 130 NM genome file in this repo, I didnot found any plasmid sequence. However the species I'm interested in contains megaplasmids! Im confused in that case should i include the plasmid sequence in the PGGB pangenome construction?

Thanks in advance

**Comment by ZoeYang2020** [comment]
Hi 
Neisseria mingitidis doesn't have plasmids. I have tested PGGB to construct plasmids graph,  it works:)

**Comment by UpalabdhaD** [comment]
Hey
Thanks for responding.

Cheers
